name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  APP_NAME: 'frontend'
  PROJECT_ID: 'jeremy-r7znm7yq'
  PROJECT_NMR: '50888160022'
  REGION: 'europe-west1'
  REGISTRY_NAME: 'run-image'
  WORKLOAD_IDENTITY_POOL: 'github-actions'
  WORKLOAD_IDENTITY_POOL_PROVIDER: 'github-provider'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2.0.0'
        with:
          workload_identity_provider: 'projects/$PROJECT_NMR/locations/global/workloadIdentityPools/$WORKLOAD_IDENTITY_POOL/providers/$WORKLOAD_IDENTITY_POOL_PROVIDER'
          service_account: 'github-wif@$PROJECT_ID.iam.gserviceaccount.com'
          project_id: '$PROJECT_ID'

      - name: Build and push the Docker image
        run: |-
          gcloud builds submit ./app \
          --tag $REGION-docker.pkg.dev/$PROJECT_ID/$REGISTRY_NAME/$APP_NAME:$GITHUB_SHA \
          --service-account=projects/$PROJECT_ID/serviceAccounts/cloudbuild-sa@$PROJECT_ID.iam.gserviceaccount.com \
          --default-buckets-behavior=REGIONAL_USER_OWNED_BUCKET

      - name: Deploy
        run: |-
          gcloud run deploy $APP_NAME \
          --region $REGION \
          --image $REGION-docker.pkg.dev/$PROJECT_ID/$REGISTRY_NAME/$APP_NAME:$GITHUB_SHA \
          --service-account=cloudrun-sa@$PROJECT_ID.iam.gserviceaccount.com
